Dashboard
Seijno/pleasurable-ui pull request #9
Opened 2024-05-17 09:24 UTC by yassirog

Dit is een Dashboard en Stakeholder pagina voor HF-Print. Je kunt hier de scores en stakeholders zien. Je kunt ook via de dashboard naar de stakeholder pagina om stakeholders toe te voegen.

Dashboard pagina:

![image](https://github.com/fdnd-task/pleasurable-ui/assets/144006281/a08a8031-2f5b-4f8d-87e1-5167ded7035c)
Dit is de dashboard pagina van een bedrijf, net als wat ik hier boven zei is dat je hier de stakeholders kan zien en de scores van de stakeholders.
(Deze pagina is nog niet af)

Stakeholder pagina:
![image](https://github.com/fdnd-task/pleasurable-ui/assets/144006281/0fe6482f-79fb-4207-86d6-e645405375fb)
Dit is de stakeholder toevoegen pagina. Je kan hier een stakeholder aan je bedrijf toevoegen.

2024-05-17 10:17 UTC, Seijno reviewed
Code ziet er goed uit! Het is een kwestie van de verschillen eronder uit vissen en samenvoegen, wel heb ik een tip om alle console.logs weg te halen die je niet meer nodig hebt. Verder dan dat, lekker bezig.

2024-05-17 10:28 UTC, suustenvoorde commented
Zorg ook dat je een homepagina hebt, en neem een gebruiker vanaf daarmee naar de verschillende routes. Je hebt nu alleen detailpagina's en dat is niet gemakkelijk om vanaf te werken. Is er ook een overview pagina?

2024-05-17 10:33 UTC, suustenvoorde commented
Het is nu nog niet responsive, zorg dat je het mobile-first opbouwt (of in ieder geval van klein scherm naar groter scherm). Kijk bijvoorbeeld eens hoe het eruit ziet op een iPad portrait mode.

2024-05-17 11:00 UTC, ju5tu5 requested changes
Loop de comments op bestanden door en schiet issues in...

2024-05-17 11:00 UTC, ju5tu5 commented on public/assets/footprint.png
Heb je deze SVG door Jake Archibalds SVGOMG heen gehaald? Daarmee optimaliseer je de paths. https://jakearchibald.github.io/svgomg/

2024-05-17 11:00 UTC, ju5tu5 commented on public/assets/handprint.png
Heb je deze SVG door Jake Archibalds SVGOMG heen gehaald? Daarmee optimaliseer je de paths. https://jakearchibald.github.io/svgomg/

2024-05-17 11:00 UTC, ju5tu5 commented on public/assets/search.svg
Heb je deze SVG door Jake Archibalds SVGOMG heen gehaald? Daarmee optimaliseer je de paths. https://jakearchibald.github.io/svgomg/

2024-05-17 11:00 UTC, ju5tu5 commented on public/script/script.js
> +const addForm = document.querySelector('form.form');
Zet ```let``` en ```const``` bovenaan, daarna de code die je programma aanzwengelt (nu op regel 2) en daarna pas functies.

2024-05-17 11:00 UTC, ju5tu5 commented on public/script/script.js
> +addForm.addEventListener('submit', submitAddFormHandler);
Dit hoort na je variabelen declaratie..

2024-05-17 11:00 UTC, ju5tu5 commented on public/style/dashboard.css
Nette indeling, duidelijk te volgen door de comments, toch is het netter om al je CSS in hetzelfde bestand te plaatsen.

2024-05-17 11:00 UTC, ju5tu5 commented on public/style/stakeholder.css
Voeg je CSS samen in 1 bestand.

2024-05-17 11:00 UTC, ju5tu5 commented on server.js
> +const apiUrl = "https://fdnd-agency.directus.app/items/";
Zet dit bovenaan bij de andere ```const``` declaraties.

2024-05-17 11:00 UTC, ju5tu5 commented on server.js
> +import express, { json } from "express";
Zet deze bovenaan bij de andere imports

2024-05-17 11:00 UTC, ju5tu5 commented on server.js
> +  const bedrijfId = request.params.id;
Deze variabelen zijn overbodig, je kunt overal gewoon ```request.body.varnaam``` gebruiken dan is ook meteen duidelijk waar het vandaan komt.

2024-05-17 11:00 UTC, ju5tu5 commented on server.js
> +  fetch("https://fdnd-agency.directus.app/items/hf_stakeholders", {
fijn dat dit werkt!

2024-05-17 11:00 UTC, ju5tu5 commented on views/dashboard.ejs
> +  <header class="menu-wrap">
Dit kan in een partial toch?

2024-05-17 11:00 UTC, ju5tu5 commented on views/dashboard.ejs
Je kunt meer onderverdelen in partials. Daarmee wordt je code overzichtelijker.

2024-05-17 11:00 UTC, ju5tu5 commented on views/partials/headdash.ejs
Apart dat je verschillende head partials hebt... Hier staan ```</body>``` en ```</html>``` in, daarmee kan er niets anders in de body staan.

2024-05-17 14:40 UTC, yassirog commented
> Zorg ook dat je een homepagina hebt, en neem een gebruiker vanaf daarmee naar de verschillende routes. Je hebt nu alleen detailpagina's en dat is niet gemakkelijk om vanaf te werken. Is er ook een overview pagina?

De dashboard pagina, komt na Tristan zijn loginpagina.

2024-05-24 08:13 UTC, Trisjan commented
- Zet voor de volgende keer een live link bij de pull request zodat we de website live kunnen zien.
- Zet de issue erbij die opgelost door deze pull request.
- [https://athenian.com/blog/why-pull-request-size-matters](https://athenian.com/blog/why-pull-request-size-matters).
- Vertel hoe je het hebt getest. (Denk aan responsive, accessibility, performance etc. (optioneel)
- Schrijf een kort stukje hoe de reviewer jouw code moet testen. (optioneel)
- We zien in de titels van je commits dat je nederlands en engels gebruikt, gebruik één van de twee talen.

Gereviewed met @Davidvboxt

2024-05-27 08:30 UTC, merged